pm.test("Response status code is 200", function () {
    pm.expect(pm.response.code).to.equal(200);
});


pm.test("Response time is less than 200ms", function () {
  pm.expect(pm.response.responseTime).to.be.below(200);
});


pm.test("Response has the required fields - userId, id, title, and body", function () {
    const responseData = pm.response.json();

    pm.expect(responseData).to.be.an('array');
    responseData.forEach(function(post) {
        pm.expect(post).to.be.an('object');
        pm.expect(post.userId).to.exist;
        pm.expect(post.id).to.exist;
        pm.expect(post.title).to.exist;
        pm.expect(post.body).to.exist;
    });
});


pm.test("Title and body are non-empty strings", function () {
    const responseData = pm.response.json();

    pm.expect(responseData).to.be.an('array').that.is.not.empty;
    
    responseData.forEach(function(post) {
        pm.expect(post.title).to.be.a('string').and.to.have.lengthOf.at.least(1, "Title should not be empty");
        pm.expect(post.body).to.be.a('string').and.to.have.lengthOf.at.least(1, "Body should not be empty");
    });
});


pm.test("UserId and id are non-negative integers", function () {
    const responseData = pm.response.json();
    
    responseData.forEach(function(post) {
        pm.expect(post.userId).to.be.a('number').and.to.be.at.least(0);
        pm.expect(post.id).to.be.a('number').and.to.be.at.least(0);
    });
});
